include_guard(GLOBAL)

function(cheryl_route_test_reports configuration)
    if(NOT TARGET module_debug_terminal_linux_impl OR NOT TARGET gtest)
        return()
    endif()
    get_target_property(already_routed gtest CHERYL_DEBUG_TERMINAL_ROUTING)
    if(already_routed)
        return()
    endif()
    get_target_property(owned gtest CHERYL_OWNED_TEST_DEPENDENCY)
    if(NOT owned)
        return()
    endif()
    get_target_property(source_root gtest SOURCE_DIR)
    set(output_root "${CMAKE_CURRENT_BINARY_DIR}/cheryl-gtest-output")
    get_filename_component(router_root "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../src" ABSOLUTE)
    file(MAKE_DIRECTORY "${output_root}/src" "${output_root}/include/gtest/internal")
    configure_file("${router_root}/gtest-output.h" "${output_root}/include/cheryl-gtest-output.h" COPYONLY)

    set(port "${source_root}/include/gtest/internal/gtest-port.h")
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${port}")
    file(READ "${port}" header)
    set(original "::std::ostream& GetStream() { return ::std::cerr; }")
    string(FIND "${header}" "${original}" stream_boundary)
    if(stream_boundary LESS 0)
        message(FATAL_ERROR "GoogleTest output routing requires review after its GTestLog stream contract changed")
    endif()
    string(REPLACE "${original}" "::std::ostream& GetStream() { return ::CE::TerminalTestDetail::error_stream(); }" header "${header}")
    string(FIND "${header}" "namespace testing {" boundary)
    if(boundary LESS 0)
        message(FATAL_ERROR "GoogleTest output routing could not locate its header declaration boundary")
    endif()
    string(SUBSTRING "${header}" 0 ${boundary} prefix)
    string(SUBSTRING "${header}" ${boundary} -1 suffix)
    file(WRITE "${output_root}/include/gtest/internal/gtest-port.h"
        "${prefix}#include \"cheryl-gtest-output.h\"\n\n${suffix}")

    foreach(name IN ITEMS gtest.cc gtest-port.cc gtest-death-test.cc gtest-test-part.cc gtest-typed-test.cc)
        set(source "${source_root}/src/${name}")
        set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${source}")
        file(READ "${source}" contents)
        string(REGEX REPLACE "([^A-Za-z0-9_:])printf\\(" "\\1::CE::TerminalTestDetail::print(" contents "${contents}")
        string(REGEX REPLACE "([^A-Za-z0-9_:])vprintf\\(" "\\1::CE::TerminalTestDetail::vprint(" contents "${contents}")
        string(REGEX REPLACE "([^A-Za-z0-9_:])fprintf\\(" "\\1::CE::TerminalTestDetail::fprint(" contents "${contents}")
        string(REPLACE "fflush(stdout)" "fflush(::CE::TerminalTestDetail::report_file(stdout))" contents "${contents}")
        string(REPLACE "fflush(stderr)" "fflush(::CE::TerminalTestDetail::report_file(stderr))" contents "${contents}")
        string(REPLACE "FileNo(stdout)" "FileNo(::CE::TerminalTestDetail::report_file(stdout))" contents "${contents}")
        string(REPLACE "::std::cout" "::CE::TerminalTestDetail::output_stream()" contents "${contents}")
        string(REPLACE "std::cout" "::CE::TerminalTestDetail::output_stream()" contents "${contents}")
        file(WRITE "${output_root}/src/${name}" "${contents}")
    endforeach()

    # The amalgamation includes src/*.cc. The original dependency checkout is untouched.
    target_include_directories(gtest BEFORE PRIVATE "$<${configuration}:${output_root}>")
    target_include_directories(gtest BEFORE PUBLIC "$<${configuration}:${output_root}/include>")
    target_sources(gtest PRIVATE "$<${configuration}:${router_root}/gtest-output.cpp>")
    set_property(TARGET gtest PROPERTY CHERYL_DEBUG_TERMINAL_ROUTING TRUE)
endfunction()
