if(TARGET Cheryl::DebugTerminal::Startup)
    return()
endif()

add_library(${TARGET_LIB_ENGINE_S_DEBUG_TERMINAL} STATIC EXCLUDE_FROM_ALL src/startup.cpp src/arguments.cpp)
add_library(Cheryl::DebugTerminal::Startup ALIAS ${TARGET_LIB_ENGINE_S_DEBUG_TERMINAL})
set_target_properties(${TARGET_LIB_ENGINE_S_DEBUG_TERMINAL} PROPERTIES
    VERSION "${VERSION_PROJECT_ENGINE}"
    OUTPUT_NAME "${OUTPUT_LIB_ENGINE_S_DEBUG_TERMINAL}"
    ARCHIVE_OUTPUT_DIRECTORY "${CHERYL_BUILD_ROOT}")
target_compile_features(${TARGET_LIB_ENGINE_S_DEBUG_TERMINAL} PUBLIC cxx_std_23)
target_include_directories(${TARGET_LIB_ENGINE_S_DEBUG_TERMINAL} PUBLIC
    "$<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include>"
    "$<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include/cheryl>")
target_compile_definitions(${TARGET_LIB_ENGINE_S_DEBUG_TERMINAL} PRIVATE
    "CHERYL_TERMINAL_AUTOMATIC=$<IF:$<CONFIG:Debug>,1,0>")
