set(CHERYL_ENGINE_TEST_ROOT "${CMAKE_CURRENT_SOURCE_DIR}")
get_filename_component(CHERYL_ENGINE_PRIVATE_SOURCE_DIR "${CMAKE_CURRENT_SOURCE_DIR}/../src" ABSOLUTE)

include(GoogleTest)
include("${CHERYL_REPOSITORY_ROOT}/cmake/CherylTests.cmake")
add_subdirectory(support)
set(CHERYL_TEST_AGGREGATE engine-all)
add_subdirectory(all-tests)
add_subdirectory(unit)
add_subdirectory(acceptance)
add_subdirectory(logging-tests)
add_subdirectory(logging-acceptance)
add_subdirectory(signal-acceptance)
