file(GLOB_RECURSE backward_check_sources CONFIGURE_DEPENDS
    "${CMAKE_CURRENT_SOURCE_DIR}/src/*.cpp")
add_executable(${TARGET_TEST_DEPENDENCY_BACKWARD_CPP} ${backward_check_sources})
set_target_properties(${TARGET_TEST_DEPENDENCY_BACKWARD_CPP} PROPERTIES
    OUTPUT_NAME "${OUTPUT_TEST_DEPENDENCY_BACKWARD_CPP}"
    RUNTIME_OUTPUT_DIRECTORY "${CHERYL_BUILD_ROOT}")
target_link_libraries(${TARGET_TEST_DEPENDENCY_BACKWARD_CPP} PUBLIC ${LINKAGE_PUBLIC_TEST_DEPENDENCY_BACKWARD_CPP})
