add_library(${TARGET_LIB_TEST_SUPPORT} INTERFACE)
target_include_directories(${TARGET_LIB_TEST_SUPPORT} INTERFACE "${CMAKE_CURRENT_SOURCE_DIR}/../include")
target_compile_definitions(${TARGET_LIB_TEST_SUPPORT} INTERFACE CHERYL_SOURCE_DIR="${CHERYL_REPOSITORY_ROOT}")
target_link_libraries(${TARGET_LIB_TEST_SUPPORT} INTERFACE ${LINKAGE_INTERFACE_LIB_TEST_SUPPORT})

add_library(${TARGET_LIB_TEST_MAIN} INTERFACE)
file(GLOB test_main_sources CONFIGURE_DEPENDS "${CMAKE_CURRENT_SOURCE_DIR}/*.cpp")
target_sources(${TARGET_LIB_TEST_MAIN} INTERFACE ${test_main_sources})
target_link_libraries(${TARGET_LIB_TEST_MAIN} INTERFACE ${LINKAGE_INTERFACE_LIB_TEST_MAIN})
