add_executable(demo src/main.cpp)
set_target_properties(demo PROPERTIES RUNTIME_OUTPUT_DIRECTORY "${CHERYL_BUILD_ROOT}")
target_compile_definitions(demo PRIVATE CHERYL_SOURCE_DIR="${CHERYL_REPOSITORY_ROOT}")
target_link_libraries(demo PRIVATE Cheryl::Engine Cheryl::NativeGLFW Cheryl::OpenGL)

if(TARGET Cheryl::UI::TGUI)
    target_sources(demo PRIVATE src/tgui-demo.cpp)
    target_compile_definitions(demo PRIVATE CHERYL_DEMO_TGUI=1)
    target_link_libraries(demo PRIVATE Cheryl::UI::TGUI)
endif()

if(TARGET Cheryl::UI::RmlUi)
    target_sources(demo PRIVATE src/rmlui-demo.cpp)
    target_compile_definitions(demo PRIVATE CHERYL_DEMO_RMLUI=1)
    target_link_libraries(demo PRIVATE Cheryl::UI::RmlUi)
endif()
