function(cheryl_add_rmlui_source)
    if(NOT EXISTS "${CHERYL_RMLUI_SOURCE}/CMakeLists.txt")
        message(FATAL_ERROR "CHERYL_RMLUI_SOURCE must point to a RmlUi 6.3 source checkout")
    endif()
    if(DEFINED RMLUI_FONT_ENGINE AND NOT RMLUI_FONT_ENGINE STREQUAL "freetype")
        message(FATAL_ERROR "Cheryl UI needs RMLUI_FONT_ENGINE=freetype; use a dedicated dependency configuration")
    endif()
    set(RMLUI_FONT_ENGINE freetype)
    set(optional_features RMLUI_SAMPLES RMLUI_TESTS RMLUI_SHELL RMLUI_LUA_BINDINGS
        RMLUI_LOTTIE_PLUGIN RMLUI_SVG_PLUGIN RMLUI_HARFBUZZ_SAMPLE
        RMLUI_IME_SAMPLE_USE_NOTO_FONTS RMLUI_TRACY_PROFILING RMLUI_CUSTOM_CONFIGURATION)
    foreach(feature IN LISTS optional_features)
        if(DEFINED ${feature} AND ${feature})
            message(FATAL_ERROR "Cheryl's owned RmlUi source requires ${feature}=OFF; supplied dependency settings are not rewritten")
        endif()
        set(${feature} OFF)
    endforeach()
    set(CMAKE_POLICY_DEFAULT_CMP0077 NEW)
    if(NOT DEFINED BUILD_SHARED_LIBS)
        set(BUILD_SHARED_LIBS OFF)
    endif()
    add_subdirectory("${CHERYL_RMLUI_SOURCE}" "${CMAKE_CURRENT_BINARY_DIR}/rmlui" EXCLUDE_FROM_ALL)
    get_directory_property(rmlui_version DIRECTORY "${CHERYL_RMLUI_SOURCE}" DEFINITION PROJECT_VERSION)
    if(NOT rmlui_version STREQUAL "6.3")
        message(FATAL_ERROR "Cheryl UI requires RmlUi 6.3; selected source reports ${rmlui_version}")
    endif()
    set(RMLUI_FONT_ENGINE freetype PARENT_SCOPE)
endfunction()
