cmake_minimum_required(VERSION 3.28)
if(CMAKE_SOURCE_DIR STREQUAL CMAKE_CURRENT_SOURCE_DIR)
    project(cheryl_audio_miniaudio_consumer LANGUAGES C CXX)
endif()
if(NOT TARGET Cheryl::Audio::Miniaudio)
    block(SCOPE_FOR VARIABLES)
        set(CHERYL_BUILD_TESTS OFF)
        set(CHERYL_BUILD_CONSUMER_TESTS OFF)
        set(CHERYL_BUILD_ROOT "${CMAKE_BINARY_DIR}")
        add_subdirectory("${CMAKE_CURRENT_LIST_DIR}/../.." audio EXCLUDE_FROM_ALL)
    endblock()
endif()
include("${CHERYL_REPOSITORY_ROOT}/cmake/CherylConsumers.cmake")
file(GLOB_RECURSE consumer_sources CONFIGURE_DEPENDS "${CMAKE_CURRENT_SOURCE_DIR}/src/*.cpp")
add_executable(${TARGET_TEST_CONSUMER_MODULE_AUDIO_MINIAUDIO} ${consumer_sources})
set_target_properties(${TARGET_TEST_CONSUMER_MODULE_AUDIO_MINIAUDIO} PROPERTIES
    OUTPUT_NAME "${OUTPUT_TEST_CONSUMER_MODULE_AUDIO_MINIAUDIO}"
    RUNTIME_OUTPUT_DIRECTORY "${CHERYL_BUILD_ROOT}")
target_link_libraries(${TARGET_TEST_CONSUMER_MODULE_AUDIO_MINIAUDIO} PRIVATE
    ${LINKAGE_PRIVATE_TEST_CONSUMER_MODULE_AUDIO_MINIAUDIO})
target_include_directories(${TARGET_TEST_CONSUMER_MODULE_AUDIO_MINIAUDIO} PRIVATE "${CMAKE_CURRENT_LIST_DIR}/../support")
add_subdirectory(headers)
add_dependencies(${TARGET_TEST_CONSUMER_MODULE_AUDIO_MINIAUDIO} ${TARGET_TEST_CONSUMER_MODULE_AUDIO_MINIAUDIO_HEADERS})
