# Discover only neutral engine dependencies; reuse targets from an enclosing build.
if(NOT TARGET Threads::Threads)
    find_package(Threads REQUIRED)
endif()
if(NOT TARGET Freetype::Freetype)
    find_package(Freetype REQUIRED)
endif()
if(NOT TARGET harfbuzz::harfbuzz)
    if(TARGET harfbuzz)
        add_library(harfbuzz::harfbuzz ALIAS harfbuzz)
    else()
        find_package(harfbuzz CONFIG QUIET)
        if(NOT TARGET harfbuzz::harfbuzz)
            find_package(PkgConfig REQUIRED)
            pkg_check_modules(CHERYL_HARFBUZZ REQUIRED IMPORTED_TARGET harfbuzz)
            add_library(harfbuzz::harfbuzz ALIAS PkgConfig::CHERYL_HARFBUZZ)
        endif()
    endif()
endif()
if(NOT TARGET ICU::uc OR NOT TARGET ICU::i18n)
    find_package(ICU REQUIRED COMPONENTS uc i18n)
endif()
if(CHERYL_BUILD_TESTS AND NOT TARGET gtest)
    add_subdirectory("${CHERYL_REPOSITORY_ROOT}/extern/googletest" extern/googletest EXCLUDE_FROM_ALL)
endif()
if(NOT TARGET ctti)
    add_subdirectory("${CHERYL_REPOSITORY_ROOT}/extern/ctti" extern/ctti EXCLUDE_FROM_ALL)
endif()
if(NOT TARGET Backward::Interface)
    set(BACKWARD_SHARED STATIC)
    add_subdirectory("${CHERYL_REPOSITORY_ROOT}/extern/backward-cpp" extern/backward-cpp EXCLUDE_FROM_ALL)
endif()
if(NOT TARGET spdlog::spdlog)
    set(SPDLOG_USE_STD_FORMAT ON)
    add_subdirectory("${CHERYL_REPOSITORY_ROOT}/extern/spdlog" extern/spdlog EXCLUDE_FROM_ALL)
endif()
if(NOT TARGET glm::glm-header-only)
    set(GLM_ENABLE_EXPERIMENTAL ON)
    add_subdirectory("${CHERYL_REPOSITORY_ROOT}/extern/glm" extern/glm EXCLUDE_FROM_ALL)
endif()
