include("${CMAKE_CURRENT_LIST_DIR}/CherylVersions.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/CherylOutputs.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/CherylLinkage.cmake")
include_guard(GLOBAL)

# A module reuses supplied targets or bootstraps one explicitly selected checkout.
# Local variable scopes suppress recursive module/demo/test selection without
# rewriting the host's cached options or compiling private engine source copies.
function(cheryl_prepare_module)
    cmake_parse_arguments(module "REQUIRES_NATIVE" "" "" ${ARGN})
    if(NOT TARGET Cheryl::Engine)
        block(SCOPE_FOR VARIABLES)
            set(CHERYL_BUILD_NATIVE_GLFW OFF)
            set(CHERYL_BUILD_OPENGL OFF)
            set(CHERYL_BUILD_UI_TGUI OFF)
            set(CHERYL_BUILD_UI_RMLUI OFF)
            set(CHERYL_BUILD_TESTS OFF)
            set(CHERYL_BUILD_CONSUMER_TESTS OFF)
            set(CHERYL_BUILD_DEMO OFF)
            add_subdirectory("${CHERYL_REPOSITORY_ROOT}" "${CMAKE_CURRENT_BINARY_DIR}/engine" EXCLUDE_FROM_ALL)
        endblock()
    endif()
    if(NOT CHERYL_BUILD_ROOT)
        set(CHERYL_BUILD_ROOT "${CMAKE_CURRENT_BINARY_DIR}")
        set(CHERYL_BUILD_ROOT "${CMAKE_CURRENT_BINARY_DIR}" PARENT_SCOPE)
    endif()
    if(CHERYL_BUILD_TESTS)
        if(NOT TARGET gtest)
            add_subdirectory("${CHERYL_REPOSITORY_ROOT}/extern/googletest" "${CMAKE_CURRENT_BINARY_DIR}/extern/googletest" EXCLUDE_FROM_ALL)
        endif()
        include("${CHERYL_REPOSITORY_ROOT}/cmake/CherylTests.cmake")
        if(NOT TARGET ${TARGET_LIB_TEST_SUPPORT})
            add_subdirectory("${CHERYL_REPOSITORY_ROOT}/projects/engine/tests/support" "${CMAKE_CURRENT_BINARY_DIR}/test-support")
        endif()
    endif()
    if(module_REQUIRES_NATIVE AND NOT TARGET Cheryl::NativeGLFW)
        if(NOT CHERYL_NATIVE_GLFW_SOURCE OR NOT EXISTS "${CHERYL_NATIVE_GLFW_SOURCE}/CMakeLists.txt")
            message(FATAL_ERROR "Supply Cheryl::NativeGLFW or CHERYL_NATIVE_GLFW_SOURCE pointing to its module directory")
        endif()
        block(SCOPE_FOR VARIABLES)
            set(CHERYL_BUILD_TESTS OFF)
            set(CHERYL_BUILD_CONSUMER_TESTS OFF)
            add_subdirectory("${CHERYL_NATIVE_GLFW_SOURCE}" "${CMAKE_CURRENT_BINARY_DIR}/native-glfw" EXCLUDE_FROM_ALL)
        endblock()
    endif()
endfunction()
