include_guard(GLOBAL)

function(cheryl_add_header_probes target library)
    cmake_parse_arguments(probe "NEUTRAL" "" "HEADERS" ${ARGN})
    set(sources)
    foreach(header IN LISTS probe_HEADERS)
        string(MAKE_C_IDENTIFIER "${header}" identifier)
        set(source "${CMAKE_CURRENT_BINARY_DIR}/${identifier}.cpp")
        set(contents "#include <${header}>\n")
        if(probe_NEUTRAL)
            string(APPEND contents "#if defined(GL_VERSION_3_3) || defined(GLFW_VERSION_MAJOR)\n#error Neutral engine headers must not include graphics or native SDKs.\n#endif\n")
        endif()
        file(WRITE "${source}" "${contents}")
        list(APPEND sources "${source}")
    endforeach()
    add_library(${target} OBJECT ${sources})
    target_link_libraries(${target} PRIVATE ${library})
endfunction()
