include_guard(GLOBAL)

# A module reuses supplied targets or bootstraps one explicitly selected checkout.
# Local variable scopes suppress recursive module/demo/test selection without
# rewriting the host's cached options or compiling private engine source copies.
function(cheryl_prepare_module)
    cmake_parse_arguments(module "REQUIRES_NATIVE" "" "" ${ARGN})
    if(NOT TARGET Cheryl::Engine)
        if(NOT CHERYL_ENGINE_SOURCE OR NOT EXISTS "${CHERYL_ENGINE_SOURCE}/CMakeLists.txt")
            message(FATAL_ERROR "Supply Cheryl::Engine or CHERYL_ENGINE_SOURCE pointing to a Cheryl checkout")
        endif()
        block(SCOPE_FOR VARIABLES)
            set(CHERYL_BUILD_NATIVE_GLFW OFF)
            set(CHERYL_BUILD_OPENGL OFF)
            set(CHERYL_BUILD_UI_TGUI OFF)
            set(CHERYL_BUILD_UI_RMLUI OFF)
            set(CHERYL_BUILD_TESTS OFF)
            set(CHERYL_BUILD_CONSUMER_TESTS OFF)
            set(CHERYL_BUILD_DEMO OFF)
            add_subdirectory("${CHERYL_ENGINE_SOURCE}" "${CMAKE_CURRENT_BINARY_DIR}/engine" EXCLUDE_FROM_ALL)
        endblock()
    endif()
    get_target_property(repository_root Cheryl::Engine CHERYL_REPOSITORY_ROOT)
    if(NOT repository_root)
        set(repository_root "${CHERYL_ENGINE_SOURCE}")
    endif()
    if(NOT repository_root)
        message(FATAL_ERROR "A supplied engine without source metadata also requires CHERYL_ENGINE_SOURCE for dependency/test helpers")
    endif()
    set(CHERYL_REPOSITORY_ROOT "${repository_root}")
    set(CHERYL_REPOSITORY_ROOT "${repository_root}" PARENT_SCOPE)
    if(NOT CHERYL_BUILD_ROOT)
        set(CHERYL_BUILD_ROOT "${CMAKE_CURRENT_BINARY_DIR}")
        set(CHERYL_BUILD_ROOT "${CMAKE_CURRENT_BINARY_DIR}" PARENT_SCOPE)
    endif()
    if(CHERYL_BUILD_TESTS)
        if(NOT TARGET gtest)
            add_subdirectory("${repository_root}/extern/googletest" "${CMAKE_CURRENT_BINARY_DIR}/extern/googletest" EXCLUDE_FROM_ALL)
        endif()
        include("${repository_root}/cmake/CherylTests.cmake")
        if(NOT TARGET cheryl_test_support)
            add_subdirectory("${repository_root}/projects/engine/tests/support" "${CMAKE_CURRENT_BINARY_DIR}/test-support")
        endif()
    endif()
    if(module_REQUIRES_NATIVE AND NOT TARGET Cheryl::NativeGLFW)
        if(NOT CHERYL_NATIVE_GLFW_SOURCE OR NOT EXISTS "${CHERYL_NATIVE_GLFW_SOURCE}/CMakeLists.txt")
            message(FATAL_ERROR "Supply Cheryl::NativeGLFW or CHERYL_NATIVE_GLFW_SOURCE pointing to its module directory")
        endif()
        block(SCOPE_FOR VARIABLES)
            set(CHERYL_BUILD_TESTS OFF)
            set(CHERYL_BUILD_CONSUMER_TESTS OFF)
            add_subdirectory("${CHERYL_NATIVE_GLFW_SOURCE}" "${CMAKE_CURRENT_BINARY_DIR}/native-glfw" EXCLUDE_FROM_ALL)
        endblock()
    endif()
endfunction()
