# Discover only neutral engine dependencies; reuse targets from an enclosing build.
if(NOT TARGET Threads::Threads)
    find_package(Threads REQUIRED)
endif()
if(NOT TARGET Freetype::Freetype)
    find_package(Freetype REQUIRED)
endif()
if(CHERYL_BUILD_TESTS AND NOT TARGET gtest)
    add_subdirectory("${CHERYL_REPOSITORY_ROOT}/extern/googletest" extern/googletest EXCLUDE_FROM_ALL)
endif()
if(NOT TARGET ctti)
    add_subdirectory("${CHERYL_REPOSITORY_ROOT}/extern/ctti" extern/ctti EXCLUDE_FROM_ALL)
endif()
if(NOT TARGET Backward::Interface)
    set(BACKWARD_SHARED STATIC)
    add_subdirectory("${CHERYL_REPOSITORY_ROOT}/extern/backward-cpp" extern/backward-cpp EXCLUDE_FROM_ALL)
endif()
if(NOT TARGET spdlog::spdlog)
    set(SPDLOG_USE_STD_FORMAT ON)
    add_subdirectory("${CHERYL_REPOSITORY_ROOT}/extern/spdlog" extern/spdlog EXCLUDE_FROM_ALL)
endif()
if(NOT TARGET glm::glm-header-only)
    set(GLM_ENABLE_EXPERIMENTAL ON)
    add_subdirectory("${CHERYL_REPOSITORY_ROOT}/extern/glm" extern/glm EXCLUDE_FROM_ALL)
endif()
