include_guard(GLOBAL)
include(GoogleTest)

function(cheryl_add_test_aggregate target)
    cmake_parse_arguments(aggregate "OWNER;EXPORT_SYMBOLS" "" "" ${ARGN})
    if(CHERYL_BUILD_ALL_TESTS)
        add_executable(${target})
    else()
        add_executable(${target} EXCLUDE_FROM_ALL)
    endif()
    set_target_properties(${target} PROPERTIES RUNTIME_OUTPUT_DIRECTORY "${CHERYL_BUILD_ROOT}")
    target_link_libraries(${target} PRIVATE cheryl_test_main)
    if(aggregate_EXPORT_SYMBOLS AND CMAKE_SYSTEM_NAME STREQUAL "Linux" AND CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang")
        target_link_options(${target} PRIVATE -rdynamic)
    endif()
    if(CHERYL_BUILD_ALL_TESTS)
        gtest_discover_tests(${target} TEST_PREFIX "${target}." WORKING_DIRECTORY "${CHERYL_BUILD_ROOT}")
    endif()
    if(aggregate_OWNER)
        set_property(GLOBAL APPEND PROPERTY CHERYL_TEST_AGGREGATES ${target})
    endif()
endfunction()

# Compile a suite's cases once, with private hooks kept on their object target.
# Each runner links case objects directly so every static test registration survives.
function(cheryl_add_test_suite target)
    cmake_parse_arguments(suite "ACCEPTANCE" "" "SOURCES;LIBRARIES;PRIVATE_INCLUDES;DEFINITIONS" ${ARGN})
    if(NOT CHERYL_TEST_AGGREGATE OR NOT TARGET "${CHERYL_TEST_AGGREGATE}")
        message(FATAL_ERROR "Create the owner's CHERYL_TEST_AGGREGATE before adding ${target}")
    endif()
    set(sources)
    foreach(source IN LISTS suite_SOURCES)
        get_filename_component(source "${source}" ABSOLUTE BASE_DIR "${CMAKE_CURRENT_SOURCE_DIR}")
        list(APPEND sources "${source}")
    endforeach()
    set(cases "${target}-cases")
    add_library(${cases} OBJECT ${sources})
    set_target_properties(${cases} PROPERTIES EXCLUDE_FROM_ALL TRUE)
    target_link_libraries(${cases} PUBLIC cheryl_test_support ${suite_LIBRARIES})
    if(suite_PRIVATE_INCLUDES)
        target_include_directories(${cases} PRIVATE ${suite_PRIVATE_INCLUDES})
    endif()
    if(suite_DEFINITIONS)
        target_compile_definitions(${cases} PRIVATE ${suite_DEFINITIONS})
    endif()
    if(suite_ACCEPTANCE AND NOT CHERYL_BUILD_ACCEPTANCE_TESTS)
        add_executable(${target} EXCLUDE_FROM_ALL)
    else()
        add_executable(${target})
    endif()
    set_target_properties(${target} PROPERTIES RUNTIME_OUTPUT_DIRECTORY "${CHERYL_BUILD_ROOT}")
    target_link_libraries(${target} PRIVATE cheryl_test_main ${cases})
    if(NOT suite_ACCEPTANCE OR CHERYL_BUILD_ACCEPTANCE_TESTS)
        gtest_discover_tests(${target} TEST_PREFIX "${target}." WORKING_DIRECTORY "${CHERYL_BUILD_ROOT}")
    endif()
    target_link_libraries(${CHERYL_TEST_AGGREGATE} PRIVATE ${cases})
    set_property(TARGET ${CHERYL_TEST_AGGREGATE} APPEND PROPERTY CHERYL_TEST_CASE_TARGETS ${cases})
endfunction()
