include_guard(GLOBAL)
include(GoogleTest)

# Owners contribute their cases and private hooks to the selected aggregate.
# Source properties keep private include access scoped to the contributing cases.
function(cheryl_add_test_suite target)
    cmake_parse_arguments(suite "ACCEPTANCE" "" "SOURCES;LIBRARIES;PRIVATE_INCLUDES;DEFINITIONS" ${ARGN})
    set(sources)
    foreach(source IN LISTS suite_SOURCES)
        get_filename_component(source "${source}" ABSOLUTE BASE_DIR "${CMAKE_CURRENT_SOURCE_DIR}")
        list(APPEND sources "${source}")
    endforeach()
    if(suite_ACCEPTANCE AND NOT CHERYL_BUILD_ACCEPTANCE_TESTS)
        add_executable(${target} EXCLUDE_FROM_ALL ${sources})
    else()
        add_executable(${target} ${sources})
    endif()
    set_target_properties(${target} PROPERTIES RUNTIME_OUTPUT_DIRECTORY "${CHERYL_BUILD_ROOT}")
    target_link_libraries(${target} PRIVATE cheryl_test_support ${suite_LIBRARIES})
    if(suite_PRIVATE_INCLUDES)
        target_include_directories(${target} PRIVATE ${suite_PRIVATE_INCLUDES})
    endif()
    if(suite_DEFINITIONS)
        target_compile_definitions(${target} PRIVATE ${suite_DEFINITIONS})
    endif()
    if(NOT suite_ACCEPTANCE OR CHERYL_BUILD_ACCEPTANCE_TESTS)
        gtest_discover_tests(${target} TEST_PREFIX "${target}." WORKING_DIRECTORY "${CHERYL_BUILD_ROOT}")
    endif()
    if(TARGET all-tests)
        target_sources(all-tests PRIVATE ${sources})
        target_link_libraries(all-tests PRIVATE ${suite_LIBRARIES})
        set_source_files_properties(${sources} TARGET_DIRECTORY all-tests PROPERTIES
            INCLUDE_DIRECTORIES "${suite_PRIVATE_INCLUDES}"
            COMPILE_DEFINITIONS "${suite_DEFINITIONS}")
    endif()
endfunction()
